name: publish

on:
  push:
    branches:
      - main # Ensure you are targeting the right branch

jobs:
  publish-reddit-api-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ghcr.io/animeshry/reddit-api:${{ github.sha }} # Use commit hash as tag (unique versioning)


      # Optional: Run container for testing purposes (if necessary)
      # - name: Run Docker container for testing
      #   run: |
      #     docker run ghcr.io/AnimeshRy/reddit-api:${{ github.sha }}
